// environments/react-native-expo/App.js
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";

import { createClient } from "contentful";

export default function App() {
  const [result, setResult] = useState("Loading...");

  useEffect(() => {
    const load = async () => {
      try {
        const client = createClient({
          // This space is for testing purposes only.
          // Never store your Contentful credentials in your projects config file.
          // Use: https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/
          space: `k8iqpp6u0ior`,
          accessToken: `hO_7N0bLaCJFbu5nL3QVekwNeB_TNtg6tOCB_9qzKUw`,
        });

        await client.getEntries();
        setResult(`✅ Success!`);
      } catch (err) {
        setResult(`🚫 Error: ${err.message}`);
        throw err;
      }
    };

    load();
  }, []);

  return (
    <View style={styles.container}>
      <Text id="loading-entries">{result}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

// environments/nuxt/app.vue
<script setup>
import ContentfulComponent from "@/components/ContentfulComponent.vue";
import * as contentful from "contentful";

let result = "Loading...";
try {
  const client = contentful.createClient({
    space: "k8iqpp6u0ior",
    accessToken: "hO_7N0bLaCJFbu5nL3QVekwNeB_TNtg6tOCB_9qzKUw",
  });

  await client.getEntries();
  result = "✅ Success!";
} catch (err) {
  console.error(`Error fetching entries: ${err.message}`);
  result = `🚫 Error: ${err.message}`;
}
</script>

<template>
  <div>
    <h1>Contentful v11 &amp; nuxtjs v3</h1>
    <h2>Core App Component using script setup</h2>
    <div id="result-script">{{ result }}</div>
    <ContentfulComponent />
  </div>
</template>
